services:
  rennan-tech:
    image: ${RENNAN_TECH_IMAGE:-rennan-tech:latest}
    container_name: rennan-tech
    restart: unless-stopped
    networks: [web]

  engineer-lab:
    image: ${ENGINEER_LAB_IMAGE:-engineer-lab:latest}
    container_name: engineer-lab
    restart: unless-stopped
    networks: [web]

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks: [web]

networks:
  web:

volumes:
  caddy_data:
  caddy_config:
