services:
  rennan-tech:
    image: ${RENNAN_TECH_ECR_URI:-public.ecr.aws/q9c0i8b3/rennan-tech}:latest
    container_name: rennan-tech
    restart: unless-stopped
    networks: [caddy]

  engineer-lab:
    image: ${ENGINEER_LAB_ECR_URI:-public.ecr.aws/q9c0i8b3/engineer-lab}:latest
    container_name: engineer-lab
    restart: unless-stopped
    networks: [caddy]

  caddy:
    image: caddy:2-alpine
    container_name: caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks: [caddy]

networks:
  caddy:

volumes:
  caddy_data:
  caddy_config:
