name: Deploy Infrastructure

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '~1.5'

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: us-east-1
          role-skip-session-tagging: true

      - id: fmt
        run: terraform fmt -check || true

      - id: init
        run: terraform init

      - id: validate
        run: terraform validate

      - id: plan
        run: |
          terraform plan -no-color -out=tfplan
          terraform show -no-color tfplan > plan.txt
          echo "plan_output<<EOF" >> $GITHUB_OUTPUT
          cat plan.txt >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment plan
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const body = `
            **Terraform results**
            fmt:      ${{ steps.fmt.outcome }}
            init:     ${{ steps.init.outcome }}
            validate: ${{ steps.validate.outcome }}
            plan:     ${{ steps.plan.outcome }}

            <details><summary>Show plan</summary>

            \`\`\`terraform
            ${{ steps.plan.outputs.plan_output }}
            \`\`\`

            </details>`;
            github.rest.issues.createComment({
              ...context.issue,
              body
            });

      - name: Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan

      - name: Propagate outputs
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          INSTANCE_ID=$(terraform output -raw instance_id)
          RENAN_REPO=$(terraform output -raw ecr_rennan_tech_repository_url)
          LAB_REPO=$(terraform output -raw ecr_engineer_lab_repository_url)

          for REPO in rennan-tech-landing engineer-lab; do
            gh secret set AWS_ACCOUNT_ID --body "$ACCOUNT_ID" --repo ${{ github.repository_owner }}/$REPO
            gh secret set AWS_REGION     --body "us-east-1"   --repo ${{ github.repository_owner }}/$REPO
            gh secret set INSTANCE_ID    --body "$INSTANCE_ID" --repo ${{ github.repository_owner }}/$REPO
          done

          gh secret set ECR_REPOSITORY_URI --body "$RENAN_REPO" --repo ${{ github.repository_owner }}/rennan-tech-landing
          gh secret set ECR_REPOSITORY_URI --body "$LAB_REPO"   --repo ${{ github.repository_owner }}/engineer-lab
